### ISSUE TITLE
Whitepaper link 404s

### ISSUE THREAD

**Issue by joepie91** [yggdrasil-network/yggdrasil-network.github.io#157]
URL: https://github.com/yggdrasil-network/yggdrasil-go/blob/master/doc/Whitepaper.md

As linked from here: https://yggdrasil-network.github.io/about.html

**Comment by LordKa0S** [comment]
Removed in: https://github.com/yggdrasil-network/yggdrasil-go/pull/781/commits/50bd16d524e3dd8ef565a8ea6ffec94473fbec8f, https://github.com/yggdrasil-network/yggdrasil-go/pull/781
